from turtle import *
setup(width=250, height=450, startx=None, starty=None)
title("新年快乐")
pencolor("red")
fillcolor("red")

penup()
goto(0,70)
pendown()
begin_fill()
circle(70, steps=4)
end_fill()

color("black")
penup()
goto(0,105)
pendown()
write("福", align="center", font=("楷体",50,"normal"))

pencolor("red")
fillcolor("red")
penup()
goto(-50,-10)
setheading(270)
pendown()
begin_fill()
for x in range (2):
    fd(120)
    rt(90)
    fd(35)
    rt(90)
end_fill()
color("black")
penup()
goto(-65,-40)
write("心", align="center", font=("楷体",20,"normal"))
goto(-65,-70)
write("想", align="center", font=("楷体",20,"normal"))
goto(-65,-100)
write("事", align="center", font=("楷体",20,"normal"))
goto(-65,-130)
write("成", align="center", font=("楷体",20,"normal"))

goto(50,-10)
pendown()
pencolor("red")
fillcolor("red")
begin_fill()
for x in range (2):
    fd(120)
    lt(90)
    fd(35)
    lt(90)
end_fill()
penup()
color("black")
goto(65,-40)
write("五", align="center", font=("楷体",20,"normal"))
goto(65,-70)
write("谷", align="center", font=("楷体",20,"normal"))
goto(65,-100)
write("丰", align="center", font=("楷体",20,"normal"))
goto(65,-130)
write("登", align="center", font=("楷体",20,"normal"))

hideturtle()
done()

#制作:权家乐  想法提供:权家乐
#版权所有 侵权必究
